import { Message } from '../types';
import { format } from 'date-fns';
import { supabase } from './supabase';

interface ChatReport {
  title: string;
  timestamp: string;
  messages: Message[];
  stats: {
    totalMessages: number;
    userMessages: number;
    assistantMessages: number;
    attachments: number;
    averageResponseTime: string;
    totalDuration: string;
  };
  user?: {
    id: string;
    email: string;
    username?: string;
    fullName?: string;
    avatarUrl?: string;
    gender?: string;
    dateOfBirth?: string;
  };
  metadata: {
    generatedAt: string;
    language: string;
    reportVersion: string;
    platform: string;
    browserInfo: string;
  };
}

export async function generateChatReport(messages: Message[], title: string, language: string = 'en'): Promise<ChatReport> {
  const timestamps = messages.map(m => new Date(m.timestamp));
  const startTime = Math.min(...timestamps.map(t => t.getTime()));
  const endTime = Math.max(...timestamps.map(t => t.getTime()));
  const duration = endTime - startTime;

  // Calculate response times between user and assistant messages
  let totalResponseTime = 0;
  let responsePairs = 0;
  for (let i = 0; i < messages.length - 1; i++) {
    if (messages[i].role === 'user' && messages[i + 1].role === 'assistant') {
      const responseTime = new Date(messages[i + 1].timestamp).getTime() - new Date(messages[i].timestamp).getTime();
      totalResponseTime += responseTime;
      responsePairs++;
    }
  }

  const stats = {
    totalMessages: messages.length,
    userMessages: messages.filter(m => m.role === 'user').length,
    assistantMessages: messages.filter(m => m.role === 'assistant').length,
    attachments: messages.filter(m => m.attachment).length,
    averageResponseTime: formatDuration(responsePairs ? totalResponseTime / responsePairs : 0),
    totalDuration: formatDuration(duration),
  };

  // Get user profile information
  let userInfo = undefined;
  try {
    const { data: userData } = await supabase.auth.getUser();
    if (userData.user) {
      const { data: profileData } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', userData.user.id)
        .single();

      userInfo = {
        id: userData.user.id,
        email: userData.user.email || 'Unknown',
        username: profileData?.username || undefined,
        fullName: profileData?.full_name || undefined,
        avatarUrl: profileData?.avatar_url || undefined,
        gender: profileData?.gender || undefined,
        dateOfBirth: profileData?.date_of_birth || undefined,
      };
    }
  } catch (error) {
    console.error('Error fetching user profile:', error);
  }

  const metadata = {
    generatedAt: format(new Date(), 'PPpp'),
    language,
    reportVersion: '1.1.0',
    platform: navigator.platform,
    browserInfo: navigator.userAgent,
  };

  return {
    title,
    timestamp: format(new Date(), 'PPpp'),
    messages,
    stats,
    user: userInfo,
    metadata,
  };
}

function formatDuration(ms: number): string {
  const seconds = Math.floor(ms / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);

  if (hours > 0) {
    return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
  } else if (minutes > 0) {
    return `${minutes}m ${seconds % 60}s`;
  } else {
    return `${seconds}s`;
  }
}

// Hindi translations for the report
const translations = {
  en: {
    title: 'Chat Report',
    generatedOn: 'Generated on',
    totalMessages: 'Total Messages',
    userMessages: 'User Messages',
    assistantMessages: 'Assistant Messages',
    attachments: 'Attachments',
    avgResponseTime: 'Avg. Response Time',
    totalDuration: 'Total Duration',
    user: 'User',
    assistant: 'Assistant',
    attachment: 'Attachment',
    userProfile: 'User Profile',
    email: 'Email',
    username: 'Username',
    fullName: 'Full Name',
    gender: 'Gender',
    dateOfBirth: 'Date of Birth',
    reportMetadata: 'Report Metadata',
    generatedAt: 'Generated At',
    language: 'Language',
    reportVersion: 'Report Version',
    platform: 'Platform',
    browserInfo: 'Browser Info',
    generatedBy: 'Generated by MindfulAI Chat',
    download: 'Download',
  },
  hi: {
    title: 'चैट रिपोर्ट',
    generatedOn: 'उत्पन्न तिथि',
    totalMessages: 'कुल संदेश',
    userMessages: 'उपयोगकर्ता संदेश',
    assistantMessages: 'सहायक संदेश',
    attachments: 'अटैचमेंट',
    avgResponseTime: 'औसत प्रतिक्रिया समय',
    totalDuration: 'कुल अवधि',
    user: 'उपयोगकर्ता',
    assistant: 'सहायक',
    attachment: 'अटैचमेंट',
    userProfile: 'उपयोगकर्ता प्रोफ़ाइल',
    email: 'ईमेल',
    username: 'उपयोगकर्ता नाम',
    fullName: 'पूरा नाम',
    gender: 'लिंग',
    dateOfBirth: 'जन्म तिथि',
    reportMetadata: 'रिपोर्ट मेटाडेटा',
    generatedAt: 'उत्पन्न समय',
    language: 'भाषा',
    reportVersion: 'रिपोर्ट संस्करण',
    platform: 'प्लेटफॉर्म',
    browserInfo: 'ब्राउज़र जानकारी',
    generatedBy: 'माइंडफुलAI चैट द्वारा उत्पन्न',
    download: 'डाउनलोड',
  }
};

export function generateHTML(report: ChatReport): string {
  const lang = report.metadata.language || 'en';
  const t = translations[lang as keyof typeof translations] || translations.en;

  return `
    <!DOCTYPE html>
    <html lang="${lang}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${t.title} - ${report.title}</title>
        <style>
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                line-height: 1.6;
                max-width: 800px;
                margin: 0 auto;
                padding: 2rem;
                background: #f7f7f7;
                color: #333;
            }
            .header {
                text-align: center;
                margin-bottom: 2rem;
                padding: 2rem;
                background: #fff;
                border-radius: 10px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .stats {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 1rem;
                margin-bottom: 2rem;
                padding: 1rem;
                background: #fff;
                border-radius: 10px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .stat-item {
                padding: 1rem;
                text-align: center;
                border: 1px solid #eee;
                border-radius: 5px;
            }
            .stat-value {
                font-size: 1.5rem;
                font-weight: bold;
                color: #2563eb;
            }
            .user-profile {
                background: #fff;
                padding: 2rem;
                border-radius: 10px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                margin-bottom: 2rem;
                display: flex;
                flex-wrap: wrap;
                gap: 1rem;
            }
            .user-avatar {
                width: 100px;
                height: 100px;
                border-radius: 50%;
                object-fit: cover;
                border: 3px solid #eee;
            }
            .user-info {
                flex: 1;
                min-width: 200px;
            }
            .user-info h3 {
                margin-top: 0;
                color: #2563eb;
            }
            .info-grid {
                display: grid;
                grid-template-columns: max-content 1fr;
                gap: 0.5rem;
            }
            .info-label {
                font-weight: bold;
                color: #666;
            }
            .metadata {
                background: #fff;
                padding: 1.5rem;
                border-radius: 10px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                margin-bottom: 2rem;
            }
            .metadata h3 {
                margin-top: 0;
                color: #2563eb;
            }
            .messages {
                background: #fff;
                padding: 2rem;
                border-radius: 10px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            }
            .message {
                margin-bottom: 1.5rem;
                padding: 1rem;
                border-radius: 5px;
            }
            .message.user {
                background: #f0f9ff;
                margin-left: 2rem;
            }
            .message.assistant {
                background: #f0fdf4;
                margin-right: 2rem;
            }
            .message-header {
                display: flex;
                justify-content: space-between;
                margin-bottom: 0.5rem;
                font-size: 0.875rem;
                color: #666;
            }
            .message-content {
                white-space: pre-wrap;
            }
            .attachment {
                margin-top: 0.5rem;
                padding: 0.5rem;
                background: #f8fafc;
                border: 1px solid #e2e8f0;
                border-radius: 4px;
                font-size: 0.875rem;
            }
            .footer {
                text-align: center;
                margin-top: 2rem;
                padding: 1rem;
                color: #666;
                font-size: 0.875rem;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>${report.title}</h1>
            <p>${t.generatedOn} ${report.timestamp}</p>
        </div>
        
        ${report.user ? `
        <div class="user-profile">
            ${report.user.avatarUrl ? `
                <img src="${report.user.avatarUrl}" alt="User avatar" class="user-avatar">
            ` : ''}
            <div class="user-info">
                <h3>${t.userProfile}</h3>
                <div class="info-grid">
                    <div class="info-label">${t.email}:</div>
                    <div>${report.user.email}</div>
                    ${report.user.username ? `
                        <div class="info-label">${t.username}:</div>
                        <div>${report.user.username}</div>
                    ` : ''}
                    ${report.user.fullName ? `
                        <div class="info-label">${t.fullName}:</div>
                        <div>${report.user.fullName}</div>
                    ` : ''}
                    ${report.user.gender ? `
                        <div class="info-label">${t.gender}:</div>
                        <div>${report.user.gender}</div>
                    ` : ''}
                    ${report.user.dateOfBirth ? `
                        <div class="info-label">${t.dateOfBirth}:</div>
                        <div>${report.user.dateOfBirth}</div>
                    ` : ''}
                </div>
            </div>
        </div>
        ` : ''}
        
        <div class="metadata">
            <h3>${t.reportMetadata}</h3>
            <div class="info-grid">
                <div class="info-label">${t.generatedAt}:</div>
                <div>${report.metadata.generatedAt}</div>
                <div class="info-label">${t.language}:</div>
                <div>${report.metadata.language === 'hi' ? 'Hindi' : 'English'}</div>
                <div class="info-label">${t.reportVersion}:</div>
                <div>${report.metadata.reportVersion}</div>
                <div class="info-label">${t.platform}:</div>
                <div>${report.metadata.platform}</div>
                <div class="info-label">${t.browserInfo}:</div>
                <div>${report.metadata.browserInfo}</div>
            </div>
        </div>
        
        <div class="stats">
            <div class="stat-item">
                <div class="stat-value">${report.stats.totalMessages}</div>
                <div>${t.totalMessages}</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${report.stats.userMessages}</div>
                <div>${t.userMessages}</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${report.stats.assistantMessages}</div>
                <div>${t.assistantMessages}</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${report.stats.attachments}</div>
                <div>${t.attachments}</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${report.stats.averageResponseTime}</div>
                <div>${t.avgResponseTime}</div>
            </div>
            <div class="stat-item">
                <div class="stat-value">${report.stats.totalDuration}</div>
                <div>${t.totalDuration}</div>
            </div>
        </div>

        <div class="messages">
            ${report.messages.map(message => `
                <div class="message ${message.role}">
                    <div class="message-header">
                        <span>${message.role === 'user' ? t.user : t.assistant}</span>
                        <span>${format(new Date(message.timestamp), 'PPpp')}</span>
                    </div>
                    <div class="message-content">${message.content}</div>
                    ${message.attachment ? `
                        <div class="attachment">
                            📎 ${t.attachment}: ${message.attachment.name} (${Math.round(message.attachment.size / 1024)}KB)
                            <br>
                            <a href="${message.attachment.url}" target="_blank">${t.download}</a>
                        </div>
                    ` : ''}
                </div>
            `).join('')}
        </div>

        <div class="footer">
            <p>${t.generatedBy}</p>
        </div>
    </body>
    </html>
  `;
}

export function downloadReport(html: string, filename: string) {
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
} 